global:
  evaluation_interval: 1m
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  – job_name: app
    static_configs:
      - targets: [ 'model.internal.com:8080' ]
        labels: 
          app_meterics